### ISSUE TITLE
demo(Development issues are discussed here.)

### ISSUE THREAD

**Issue by denstiny** [nvim-zh/colorful-winsep.nvim#1]
![图片](https://user-images.githubusercontent.com/57088952/198960392-ced352c9-2e93-4726-8c74-eab5251b42f8.png)

**Comment by denstiny** [comment]
https://user-images.githubusercontent.com/57088952/198973680-77c6d8f7-73fa-40a8-9c98-1f1d56defeb7.mp4

**Comment by denstiny** [comment]
https://user-images.githubusercontent.com/57088952/200179908-8baee8ac-3f4f-4110-88f7-5d8a1272213c.mp4

**Comment by real-fht** [comment]
Hi, amazing plugin!

Is it possible to lazy-load it?

**Comment by denstiny** [comment]
> Hi, amazing plugin!
> 
> Is it possible to lazy-load it? Already tried some possibilities in specifying the plugin using packer.nvim but nothing good for now

I don't understand it, so I don't know how to start, if you can provide relevant documents, I can learn

**Comment by real-fht** [comment]
> > Hi, amazing plugin!
> > Is it possible to lazy-load it? Already tried some possibilities in specifying the plugin using packer.nvim but nothing good for now
> 
> I don't understand it, so I don't know how to start, if you can provide relevant documents, I can learn

Nevermind, I found a way to achieve the behaviour I want.

Thanks for your reply and attention though!

**Comment by denstiny** [comment]
https://user-images.githubusercontent.com/57088952/234891291-e0657633-eec8-40f7-b512-1da29c01ac05.mp4
