### ISSUE TITLE
Not working correctly with vim-tpipeline

### ISSUE THREAD

**Issue by bondzula** [nvim-zh/colorful-winsep.nvim#10]
I'm using `vim-tpipeline` to render the neovim statusline in tmux statusline, so i guess that is confusing the winsep, here is how it looks

![2022-11-02_12-34](https://user-images.githubusercontent.com/18123522/199479757-c88ddd11-165b-4d13-9c10-8e0cc18595b7.png)

**Comment by denstiny** [comment]
hi, I'm not familiar with tmux, can you tell me how to know I'm currently in a tmux environment?

**Comment by bondzula** [comment]
Hi, sorry for late reply, I'm not sure how to do it with lua, but what i do know is that tmux sets `$TMUX` env variable when running, maybe you can use that?

**Comment by denstiny** [comment]
_Please provide your vim configuration, I need laststatus，cmdheight

**Comment by bondzula** [comment]
```viml
laststatus=3
cmdheight=1
```

**Comment by denstiny** [comment]
![图片](https://user-images.githubusercontent.com/57088952/201006933-e780cc19-f8d5-4df2-acc5-e6649ace0815.png)

**Comment by denstiny** [comment]
hi, I didn't find the problem, please update the latest version and try again, I'm not sure if this problem is fixed when modifying other problems
