### ISSUE TITLE
Not compatible with mouse for resizing

### ISSUE THREAD

**Issue by wookayin** [nvim-zh/colorful-winsep.nvim#11]
When mouse is enabled (`set mouse=a`), one can left-click the window border and drag around to resize the window. However, when the border is visible (which is a floating window), mouse can't be used for resizing. We probably may need to emulate the mouse behavior.

**Comment by jonatan-branting** [comment]
You can fix this by setting `focusable = false

**Comment by denstiny** [comment]
ok i'll try it

**Comment by denstiny** [comment]
> This should be fixable by simply setting `focusable = false` when configuring that floating windows that contain the separators.

Thank you for your help
