### ISSUE TITLE
Remove default notification spam

### ISSUE THREAD

**Issue by jemag** [nvim-zh/colorful-winsep.nvim#14]
Seems like https://github.com/nvim-zh/colorful-winsep.nvim/commit/112c73265f3edcfc989408d085aec6f6be82631a#diff-f91d374d8a5d29281a06126fb34125af0dc154e1e3245d87eabb619e70a47973R11-R18
![image](https://user-images.githubusercontent.com/7985687/200190985-f964d4e5-5698-4f2d-904c-73c736fcf078.png)

added notification spam by default. Any particular reason why that is?

**Comment by denstiny** [comment]
You need to set your own close_event and create_event,
They are executed after creating the split line and closing the split line respectively


```lua
setup({
  highlight = {
    guibg = "#16161E",
    guifg = "#1F3442"
  },
  interval = 30,
  no_exec_files = { "packer", "TelescopePrompt", "mason", "CompetiTest", "NvimTree" },
  symbols = { "━", "┃", "┏", "┓", "┗", "┛" },
  close_event = function()
  end,
  create_event = function()
  end
})
```

**Comment by jemag** [comment]
@denstiny I am aware, however I still find it strange that anyone who install with the default approach of 
`require('colorful-winsep').setup({})`
will get this notification spam.

Seems not optimal to have this as the default behavior.

**Comment by denstiny** [comment]
ok i think you are right i will fix it right away

**Comment by denstiny** [comment]
ok, i have updated it, thanks for your suggestion
