### ISSUE TITLE
[feature request] `min_windows` option

### ISSUE THREAD

**Issue by garcia5** [nvim-zh/colorful-winsep.nvim#15]
I love this plugin when I have at least 3 windows visible, it makes it a lot easier to identify where I am. However, if I only have 2 windows open, this plugin doesn't really do a whole lot for me. The separator stays constant and just flickers when I move between the two splits.

I think it would be useful to provide a config option to specify the minimum number of visible windows required to enable the border.

```lua
{
  -- ...
  -- only enable the border if there are at least this many windows visible
  min_windows = 2,
}
```

**Comment by denstiny** [comment]
hi， you can use `create_event`

**Comment by denstiny** [comment]
## demo
```lua
local _, colorful_winsep = pcall(require, "colorful-winsep")
if not _ then return end
colorful_winsep.setup({
  create_event = function()
    if vim.fn.winnr('$') == 3 then
      colorful_winsep.NvimSeparatorDel()
    end
  end
})
```

**Comment by garcia5** [comment]
Thanks, that works perfectly!

**Comment by denstiny** [comment]
hi, this is just to provide a simple idea, in fact, there is a problem with this method, such as when vim.notify sends an email, it will not work, you need to filter the notify window count

**Comment by denstiny** [comment]
Now you can try the latest version, when there are only two windows
