### ISSUE TITLE
The default for the background highlight of `bg` is not a valid colour

### ISSUE THREAD

**Issue by megalithic** [nvim-zh/colorful-winsep.nvim#2]
The error:

`Error executing vim.schedule lua callback: .../start/colorful-winsep.nvim/lua/colorful-winsep/init.lua:229: Vim(append):Error executing lua callback: .../start/colorful-winsep.nvim/lua/colorful-winsep/init.lua:23: 'bg' is not a valid color`

https://github.com/nvim-zh/colorful-winsep.nvim/blob/main/lua/colorful-winsep/init.lua#L16

**Comment by denstiny** [comment]
I got it. You can temporarily change it to another color.

**Comment by tobealive** [comment]
`vim.api.nvim_get_hl_by_name("Normal", true)["background"]` instead of `bg` on: https://github.com/nvim-zh/colorful-winsep.nvim/blob/95143b141ba9ab3739fbedf3fdb4003dc52c75b4/lua/colorful-winsep/init.lua#L16 keeps the same functionality plus allows `nil` (transparent) values.

**Comment by denstiny** [comment]
> `vim.api.nvim_get_hl_by_name("Normal", true)["background"]`代替 `"bg"`上：
> 
> https://github.com/nvim-zh/colorful-winsep.nvim/blob/95143b141ba9ab3739fbedf3fdb4003dc52c75b4/lua/colorful-winsep/init.lua#L16
> 保持相同的功能加上允许 `nil`（透明）值。

I don't understand, I set "bg" it works

**Comment by denstiny** [comment]
> `vim.api.nvim_get_hl_by_name("Normal", true)["background"]`代替 `"bg"`上：
> 
> https://github.com/nvim-zh/colorful-winsep.nvim/blob/95143b141ba9ab3739fbedf3fdb4003dc52c75b4/lua/colorful-winsep/init.lua#L16
> 保持相同的功能加上允许 `nil`（透明）值。

I took your advice, thank you
