### ISSUE TITLE
Highlight color config not working

### ISSUE THREAD

**Issue by jeeeem** [nvim-zh/colorful-winsep.nvim#20]
I'm trying to change the color of the window separator in the config but its not working, but manually changing the highlight group `NvimSeparator` works

- highlight config `#111111` but its still using the `#a9b1d6` for some reason

![image](https://user-images.githubusercontent.com/51053482/202886305-12b88d83-05cb-43dc-b562-d74743bcc602.png)

- did the `highlight NvimSeparator guifg=#a94dc1`

![image](https://user-images.githubusercontent.com/51053482/202886350-6f761b9c-7863-48e6-8198-b5d8b340a1ad.png)

**Comment by denstiny** [comment]
colortheme theme name will clear the highlight group, when winsep is executed after colortheme, it will not be able to set an empty highlight group

**Comment by epigramengineer** [comment]
Also now I can't set the highlight group in my custom theme which I would very much like to be able to do.

**Comment by denstiny** [comment]
> I'm running into the same issue, even with the latest fix pulled in.

https://github.com/nvim-zh/colorful-winsep.nvim/blob/main/lua/colorful-winsep/init.lua#L48-L48

I was careless. I'll fix him as soon as I can
