### ISSUE TITLE
Highlighting with `cterm` colors getting overridden

### ISSUE THREAD

**Issue by Amar1729** [nvim-zh/colorful-winsep.nvim#21]
In my (vimscipt) config with previous commit https://github.com/nvim-zh/colorful-winsep.nvim/tree/9a474934a27203d1c2e9943c94a29165dd81823d, i configured colorful-winsep like this:

```vim
" use color 2 for the new window border
lua require('colorful-winsep').setup()
hi NvimSeparator ctermfg=2
```

(I currently use neovim with `termguicolors` off)

As of https://github.com/nvim-zh/colorful-winsep.nvim/issues/20, the `NvimSeparator` highlight gets overridden on `ColorScheme` and `WinEnter` events ([here](https://github.com/nvim-zh/colorful-winsep.nvim/blob/bb06c8678b1f879f14264aaba721098cc5495768/lua/colorful-winsep/init.lua)).

Since the setup doesn't allow for using `cterm` colors, only `gui` colors, I can't set this color in the setup, so this is the workaround I am currently using:

```lua
local group_postwinsep = vim.api.nvim_create_augroup(
    "NvimSeparatorPost", { clear = true }
)

vim.api.nvim_create_autocmd("WinEnter",
    {
        group = group_postwinsep,
        callback = function(opts) vim.cmd [[ hi NvimSeparator ctermfg=2 ]] end,
    }
)
```

Not sure if there's a better way to do this, or if there's a good solution for how the `view.highlight` code is organized?

Thanks for the plugin! I appreciate the how clean it makes splits look.

**Comment by denstiny** [comment]
Sorry, just saw your issues, I'm not sure how to fix it

**Comment by denstiny** [comment]
I try to refactor view.highlight

**Comment by denstiny** [comment]
now you can setting `ctermfg`
```lua
colorful_winsep.setup({
  highlight = {
    fg = "#9898B5",
    bg = "#0D0F18",
    ctermfg = 2
  }
})
```

**Comment by Amar1729** [comment]
Thank you!
