### ISSUE TITLE
Invalid key key: guifg

### ISSUE THREAD

**Issue by jeeeem** [nvim-zh/colorful-winsep.nvim#23]
![image](https://user-images.githubusercontent.com/51053482/208297300-f96ae7f4-0f7b-48d5-a52e-55514d5d25aa.png)

![image](https://user-images.githubusercontent.com/51053482/208297379-0324876b-8efa-406f-8973-00544481b03d.png)

Nvim version: NVIM v0.9.0-dev-505+ga6b05cb75

**Comment by smackesey** [comment]
I ran into this, was able to fix it by changing the `highlight.guibg` and `highlight.guifg` keys in my config to `highlight.bg` and `highlight.fg`. Plugin update appears to have changed the keys without deprecation warning.

**Comment by denstiny** [comment]
> I ran into this, was able to fix it by changing the `highlight.guibg` and `highlight.guifg` keys in my config to `highlight.bg` and `highlight.fg`. Plugin update appears to have changed the keys without deprecation warning.

Deprecation warning, what should I do

**Comment by smackesey** [comment]
If you use `highlight` in your config, make sure you use `bg`/`fg` and not `guibg`/`guifg`:

```
require('colorful-winsep').setup({

  highlight = {
    bg="#539bf5",
    fg="#539bf5",
  },

})
```

**Comment by denstiny** [comment]
> > what should I do
> 
> If you use `highlight` in your config, make sure you use `bg`/`fg` and not `guibg`/`guifg`:
> 
> ```
> require('colorful-winsep').setup({
>   highlight = {
>     bg="#539bf5",
>     fg="#539bf5",
>   },
> })
> ```

hi,i'm zuthor!

**Comment by denstiny** [comment]
> I ran into this, was able to fix it by changing the `highlight.guibg` and `highlight.guifg` keys in my config to `highlight.bg` and `highlight.fg`. Plugin update appears to have changed the keys without deprecation warning.


Following your advice, I just added it
![图片](https://user-images.githubusercontent.com/57088952/208301963-15a989a9-d3e3-47e6-a816-46f3d74b0c06.png)
