### ISSUE TITLE
Need add default opts when setup opts is nil.

### ISSUE THREAD

**Issue by PHSix** [nvim-zh/colorful-winsep.nvim#24]
Here maybe need add a default opts when opts is nil, if without will case a bug  when startup.

code:
https://github.com/nvim-zh/colorful-winsep.nvim/blob/39ecad52911cd4c4383e935be7724e30878e96ef/lua/colorful-winsep/init.lua#L30

error message:
Error in packer_compiled: ...rt/colorful-winsep.nvim/lua/colorful-winsep/comments.lua:19: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by Allaman** [comment]
...or update the README to 

```
  {
    "nvim-zh/colorful-winsep.nvim",
    config = function()
      require("colorful-winsep").setup({})
    end,
  },
```

(notice the empty table as argument to setup)
