### ISSUE TITLE
Opening `q:` will show an error

### ISSUE THREAD

**Issue by jeeeem** [nvim-zh/colorful-winsep.nvim#27]
![image](https://user-images.githubusercontent.com/51053482/212333265-fc3e9f7d-3b9d-4c82-ad41-c22f50128ef7.png)

**Context:**
I have this `create-event` function in my config that causing the error. 

**Steps to Reproduce**:
Opening neovim with only one window and open the command history will reproduce the error, but opening the command history with more than 1 window will not.

![image](https://user-images.githubusercontent.com/51053482/212333544-758c6819-4c52-495b-9ea9-0b5a0fb3c9db.png)

**Neovim Version:**
NVIM v0.9.0-dev-647+g1df2db0bc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az612-44

**Comment by denstiny** [comment]
I might have to look at the 0.9 changes, I haven't tried 0.9nvim yet

**Comment by denstiny** [comment]
https://user-images.githubusercontent.com/57088952/212446634-bbb768a9-8199-4595-bc01-c0d9d50346eb.mp4
i can't reproduce

**Comment by denstiny** [comment]
https://github.com/neovim/neovim/issues/21171

**Comment by denstiny** [comment]
My mistake,It should be solved [8eba4fdfe82371c7ec8ef5e0015f97545f923c3f](https://github.com/nvim-zh/colorful-winsep.nvim/commit/8eba4fdfe82371c7ec8ef5e0015f97545f923c3f)

**Comment by denstiny** [comment]
https://user-images.githubusercontent.com/57088952/212449884-dcc56aed-8590-4662-8962-9560fe4a6e15.mp4

Demonstration effect

**Comment by jeeeem** [comment]
Just updated it, but I encounter another error when only just opening the neovim

![image](https://user-images.githubusercontent.com/51053482/212461930-c2627a57-c9fa-4cf6-aa29-e1736bca5bf4.png)

**Comment by jeeeem** [comment]
Never mind its already been fixed, I just check docs and code, you change the API name. `calculate_number_windows()` Thanks for the fixed.

**Comment by denstiny** [comment]
> Just updated it, but I encounter another error when only just opening the neovim
> 
> ![image](https://user-images.githubusercontent.com/51053482/212461930-c2627a57-c9fa-4cf6-aa29-e1736bca5bf4.png)
> 

You didn't install vim-notify.
