### ISSUE TITLE
[Feature request] Highlight outer border

### ISSUE THREAD

**Issue by oblitzitate** [nvim-zh/colorful-winsep.nvim#28]
I use 2 window v-splits most of the time so the inner window border highlights often don't provide good feedback for me (given a global statusline). Having the outer border highlighted also would solve this.

**Comment by denstiny** [comment]
> I use 2 window v-splits most of the time so the inner window border highlights often don't provide good feedback for me (given a global statusline). Having the outer border highlighted also would solve this.

In fact, I didn't find a better display method, any display method will block other components, such as winbar, statusline

**Comment by denstiny** [comment]
I hope you can provide a better display

**Comment by oblitzitate** [comment]
Maybe the following repo can help as inspiration: https://github.com/b0o/incline.nvim

**Comment by denstiny** [comment]
> Maybe the following repo can help as inspiration: https://github.com/b0o/incline.nvim
> 
> Also noice.nvim's classic bottom cmdline is able to overlay a floating window on top of the statusline: https://github.com/folke/noice.nvim

Floating window cannot be moved to the winbar and cmdline
