### ISSUE TITLE
Trying to change background color but it doesnt seem to work.

### ISSUE THREAD

**Issue by thepenguinthatwants** [nvim-zh/colorful-winsep.nvim#29]
Hiya,
Your plugin is amazing as it makes it lot quicker to check which terminal is focused.
The problem is that the color is not that nice.
I am using lazy as nvim package manager.

I've tried to change background color but it doesn't seem to do anything with this.
```
return {
  "nvim-zh/colorful-winsep.nvim",
  config = true,
        highlight = {
                bg = '#4974a5',
                fg = '#4974a5'
        },

}
```'¨
Can you help?

**Comment by denstiny** [comment]
It seems that this is not the right lazy. Nvim use way
![图片](https://user-images.githubusercontent.com/57088952/222676889-f2b9749c-74bc-4a0e-8218-454f29ae0305.png)

```lua
	{
		"nvim-zh/colorful-winsep.nvim",
		config = function()
			asynrequire("packers.nvimsep")
		end,
		event = { "WinNew" },
	}
```lua

**Comment by thepenguinthatwants** [comment]
I managed to install winsep, but not sure based on your picture how I should've set it up differently.

**Comment by thepenguinthatwants** [comment]
{
    "nvim-zh/colorful-winsep.nvim",
    lazy = false,
    config = function ()
      require("colorful-winsep").setup({
        highlight = {
          bg = "#282828",
          fg = "#d8a657",
        },
        interval = 30,
        no_exec_files = { "packer", "TelescopePrompt", "mason", "CompetiTest", "NvimTree" },
        symbols = { "━", "┃", "┏", "┓", "┗", "┛" },
        close_event = function()
        end,
        create_event = function()
        end,
      })
    end
  }

also fails

**Comment by thepenguinthatwants** [comment]
ah u r right thanks!

**Comment by denstiny** [comment]
> 

you are welcome

**Comment by denstiny** [comment]
> ah u r right thanks!

you are welcome
