### ISSUE TITLE
Error when opening harpoon list

### ISSUE THREAD

**Issue by catgoose** [nvim-zh/colorful-winsep.nvim#3]
Error:

`Error executing vim.schedule lua callback: .../start/colorful-winsep.nvim/lua/colorful-winsep/init.lua:232: Vim(wincmd):E16: Invalid range: 5 wincmd w
stack traceback:
        [C]: in function 'nvim_command'
        .../start/colorful-winsep.nvim/lua/colorful-winsep/init.lua:232: in function 'direction_have'
        .../start/colorful-winsep.nvim/lua/colorful-winsep/init.lua:129: in function 'create_float_win'
        .../start/colorful-winsep.nvim/lua/colorful-winsep/init.lua:38: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>`

What is interesting is the harpoon command list opens fine:
![image](https://user-images.githubusercontent.com/21010072/199087434-fb5e5124-8c2f-4ca1-a814-653d1192f4ff.png)

Would it be possible to pass a file type exclusion table to the setup function?

**Comment by tobealive** [comment]
```lua
no_exec_files = { "packer", "TelescopePrompt", "mason", "CompetiTest", "neo-tree", "harpoon" },
```

you already can do that 👍

**Comment by tobealive** [comment]
But floating windows generally seem to be problematic.

For some it seems they can't be specified as exception. E.g., rename dialogs or a tree. Neo-tree in my case. 

lspsaga-rename can be excepted with `"sagarename"` but passing empty filetype to the list `""`  to fix it for neo-trees dialogs doesn't seem to work currently. There are probably a lot of related examples.

**Comment by denstiny** [comment]
> 但浮动窗口通常似乎是有问题的。
> 
> 对于某些人来说，它们似乎不能被指定为例外。 例如，重命名对话框或过滤树中的对话框。 就我而言，新树。
> 
> lspsaga-rename 可以例外 `"sagarename"`但将空文件类型传递给列表 `""`为新树对话框修复它目前似乎不起作用。 可能有很多相关的例子。

I don't think other floating windows need it, I will skip all floating windows
