### ISSUE TITLE
Typo in the Lazy instructions?

### ISSUE THREAD

**Issue by MangelMaxime** [nvim-zh/colorful-winsep.nvim#31]
Hello,

I think there is an error in the Lazy instructions:

```lua
	{
		"nvim-zh/colorful-winsep.nvim",
		config = function()
			asynrequire("packers.nvimsep")
		end,
		event = { "WinNew" },
	}
```

Should `asynrequire("packers.nvimsep")` be `require("colorful-winsep").setup()`?

**Comment by denstiny** [comment]
Thanks for reminding

**Comment by MangelMaxime** [comment]
I am not sure about the fix you applied.

The name of the package seems incorrect and also we don't need to call the `setup` function?

**Comment by denstiny** [comment]
> I am not sure about the fix you applied.
> 
> The name of the package seems incorrect and also we don't need to call the `setup` function?

no problem
