### ISSUE TITLE
Indistinguishable highlighting on two vertical/horizontal splits

### ISSUE THREAD

**Issue by andrhua** [nvim-zh/colorful-winsep.nvim#33]
Is it possible to simulate tmux behaviour to highlight only a half of window border?
![image](https://user-images.githubusercontent.com/15843809/228898774-8a266cde-29b6-4086-8870-79b157aba03c.png)
![image](https://user-images.githubusercontent.com/15843809/228898923-b0da9ba6-1b09-421e-be92-543af61d2854.png)

**Comment by denstiny** [comment]
There is no problem with this implementation, but how to distinguish, I have not used tmux, and I do not understand this mechanism

**Comment by denstiny** [comment]
Look at this [When the window has two only](https://github.com/nvim-zh/colorful-winsep.nvim/pull/45)
