### ISSUE TITLE
Error when start: attempt to call field 'nvim_get_hl' (a nil value)

### ISSUE THREAD

**Issue by Hanaasagi** [nvim-zh/colorful-winsep.nvim#35]
Sometimes an error is reported when starting nvim.

```
/home/kumiko/.config/nvim/lua/plugins/ui.lua:6: Vim(append):Error executing lua callback: ...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:129: attempt to call field 'nvim_get_hl' (a nil value)

```

![2023-04-12_12-24](https://user-images.githubusercontent.com/9482395/231349195-e05eea42-6f8b-4598-8829-0be05ae5508e.png)

Plugin commit sha: 9270b5f79bdfb6aed2807d073389954a7fc3e9c6
Neovim version: 0.8.3

**Comment by denstiny** [comment]
Thank you for your willingness to contribute code to winsep.
