### ISSUE TITLE
After using the latest code, there is an error message when I  split window

### ISSUE THREAD

**Issue by guxuerui** [nvim-zh/colorful-winsep.nvim#37]
Hello~  I'm using your plugin, and I saw that you have submitted the latest code. However, when I use `lazy.nvim` update, I get the following error every time I start up the split screen👇🏻

![image](https://user-images.githubusercontent.com/23629097/231391106-22a2fb69-4a18-4e64-bca4-b2634ba264fd.png)

 And I am using the default configuration: 
 
 ```lua
 {
    "nvim-zh/colorful-winsep.nvim",
    config = true,
    event = { "WinNew" },
}
 ```

Everything went back to normal after I removed it，what can I do to solve this question?    Thank you very much！

**Comment by denstiny** [comment]
＃36

**Comment by denstiny** [comment]
Well, I'll fix it later.

**Comment by denstiny** [comment]
I tested version 0.8 and 0.9 and there is no problem

**Comment by guxuerui** [comment]
> I tested version 0.8 and 0.9 and there is no problem

Well, I'm using nvim 0.8 and I will try again later

**Comment by guxuerui** [comment]
I don't know why, but even after I uninstalled and reinstalled, the error still exists...

**Comment by denstiny** [comment]
Can you provide minimal reproducible code

**Comment by guxuerui** [comment]
> Hello~ I'm using your plugin, and I saw that you have submitted the latest code. However, when I use `lazy.nvim` update, I get the following error every time I start up the split screen👇🏻
> 
> ![image](https://user-images.githubusercontent.com/23629097/231391106-22a2fb69-4a18-4e64-bca4-b2634ba264fd.png)
> 
> And I am using the default configuration:
> 
> ```lua
> {
>    "nvim-zh/colorful-winsep.nvim",
>    config = true,
>    event = { "WinNew" },
> }
> ```
> 
> Everything went back to normal after I removed it，what can I do to solve this question? Thank you very much！

Just like this, I excute `Lazy.nvim`'s command:  Clean and  Install

**Comment by denstiny** [comment]
https://user-images.githubusercontent.com/57088952/231440493-7ac83152-1f15-4470-be77-c80645b710f9.mp4



> > Hello~ I'm using your plugin, and I saw that you have submitted the latest code. However, when I use `lazy.nvim` update, I get the following error every time I start up the split screen👇🏻
> > ![image](https://user-images.githubusercontent.com/23629097/231391106-22a2fb69-4a18-4e64-bca4-b2634ba264fd.png)
> > And I am using the default configuration:
> > ```lua
> > {
> >    "nvim-zh/colorful-winsep.nvim",
> >    config = true,
> >    event = { "WinNew" },
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Everything went back to normal after I removed it，what can I do to solve this question? Thank you very much！
> 
> Just like this, I excute `Lazy.nvim`'s command: Clean and Install
> 
> Also have this error
> 
> ![image](https://user-images.githubusercontent.com/23629097/231438220-3e6c6817-c662-4e46-9461-9a77d3a1ebef.png)

**Comment by guxuerui** [comment]
> I can't reproduce,I'm very sorry

Ok, perhaps this problem will disappear tomorrow😂 I will try again more times, Thank you very much for your response.

**Comment by guxuerui** [comment]
> I can't reproduce,I'm very sorry

I think I know the reason, but I’m not sure if it’s because of it. I found a piece of code in view.lua:

![image](https://user-images.githubusercontent.com/23629097/231637611-f6403aa8-7c14-435e-ab5a-7063c8c2635b.png)

Then, I installed Neovim version 0.8.3 and the error disappeared.

Finally, I created a simple PR #38  to update the required version information for Neovim from 0.8.0 to 0.8.3, hoping that this would help people more easily understand and resolve this issue.

**Comment by denstiny** [comment]
> > I can't reproduce,I'm very sorry
> 
> I think I know the reason, but I’m not sure if it’s because of it. I found a piece of code in `view.lua`:
> 
> ![image](https://user-images.githubusercontent.com/23629097/231637611-f6403aa8-7c14-435e-ab5a-7063c8c2635b.png)
> 
> Then, I installed Neovim version 0.8.3 and the error disappeared.
> 
> Finally, I created a simple PR #38 to update the required version information for Neovim from 0.8.0 to 0.8.3, hoping that this would help people more easily understand and resolve this issue.

ok,I received, seems I not rigorous testing way
