### ISSUE TITLE
statusline overlaps separator when splitting horizontally

### ISSUE THREAD

**Issue by jfmoulin** [nvim-zh/colorful-winsep.nvim#40]
Fantastic idea!

Just one thing still bothers me (a little): I am using a statusline (lualine) and when splitting horizontally, it overlaps the window separator.
![colorful_winsep](https://user-images.githubusercontent.com/2844284/232336823-645334c5-e5fb-4373-8383-f975d09948b3.png)

**Comment by denstiny** [comment]
For special reasons, A friend of mine doesn't want winsep to block statusline,.So winsep will not overwrite statusline. If you want to achieve the demonstration effect, you should set it to laststatus 3

**Comment by jfmoulin** [comment]
I also would not like to see the statusline disturbed. Maybe there is still a solution though: you could trace the horizontal line at the top of the lower window. So you would decorate 2 windows rather than one but would achieve the desired result.
In poor ASIIART:

     ___________
    |                |
    |   topwin |
    ....status....
     ___________
        
         botwin
    ....status....

**Comment by denstiny** [comment]
I don't understand, can you draw a demo

**Comment by jfmoulin** [comment]
Here we go:
We want to decorate the top window (green one) and have the problem that its statusline would be painted over by the lower horizontal separator.
I suggest to draw only the left, top and right separators for the green window
and a top separator for the red window.
This way, top window is surrounded by separators and statusline is untouched.
![scheme_small](https://user-images.githubusercontent.com/2844284/232543758-6c6440b1-4f63-4623-90ab-29d8de6ed63d.png)

**Comment by denstiny** [comment]
> Here we go:
> We want to decorate the top window (green one) and have the problem that its statusline would be painted over by the lower horizontal separator.
> I suggest to draw only the left, top and right separators for the green window
> and a top separator for the red window.
> This way, top window is surrounded by separators and statusline is untouched.
> ![scheme_small](https://user-images.githubusercontent.com/2844284/232543758-6c6440b1-4f63-4623-90ab-29d8de6ed63d.png)
> 

This is a great idea, but the horizontal dividing line will block the red window.

**Comment by denstiny** [comment]
The statusline 3 is the most appropriate

**Comment by jfmoulin** [comment]
yes... that statusline = 3 is ok, although I have been used to having my statusline direct under the window.
Anyway, thx for the plugin and your answers.
If you do not have any further comments, you may close.

**Comment by denstiny** [comment]
> yes... that statusline = 3 is ok, although I have been used to having my statusline direct under the window.
> Anyway, thx for the plugin and your answers.
> If you do not have any further comments, you may close.
> 

yes
