### ISSUE TITLE
Error: Window  was closed immediately

### ISSUE THREAD

**Issue by mojasp** [nvim-zh/colorful-winsep.nvim#42]
I am getting the following error
![image](https://user-images.githubusercontent.com/9821375/232444201-13f56f54-39ad-4c18-944f-dfacaeaa94b3.png)

when using the command `:TaskWikiChoseTag` from [taskwiki](https://github.com/tools-life/taskwiki). The command is suposed to open an interactive vertical split. The split instead closes as soon as Enter (to acknowledge the erorr message) is pressed.

I can investigate later.

**Comment by denstiny** [comment]
I have received, this two days are very busy, you need to wait

**Comment by denstiny** [comment]
I'm sorry, but I refused to read the python code
