### ISSUE TITLE
Set nofile

### ISSUE THREAD

**Issue by Maverun** [nvim-zh/colorful-winsep.nvim#5]
This plugins have potentially, but problem is that
if you try `:qa`
You wouldn't able to quit since it will complain about no write since last change or something

so you need to set `nofile` for each of those floating window

![colofulwinsep](https://user-images.githubusercontent.com/17103748/199162327-dad7da9d-4a95-46bc-887c-106cd397eed6.gif)

**Comment by denstiny** [comment]
Received, thank you for your feedback

**Comment by jdhao** [comment]
@Maverun  Please check the latest release to see if the issue is resolved.

**Comment by Maverun** [comment]
It work as it should be. Thanks
