### ISSUE TITLE
WinSeparator doesnt respect statusline

### ISSUE THREAD

**Issue by TLSingh1** [nvim-zh/colorful-winsep.nvim#50]
Hey fam, Tysm for this plugin.

Everything was working perfectly until I accidently set via command :set signcolumn=number, and now I have this bug. Resetting back to :set signcolumn=yes didn't revert the bug :( 

Prior to this, I set signcolumn=yes via vim api. 

As the title suggests, when I am vsplit 2 windows, the winSeparator doesnt respect the status line as seen in this image.

![winseptop](https://github.com/nvim-zh/colorful-winsep.nvim/assets/89089655/77e08e3e-0d93-45e2-a903-c58f2ef1b755)
![winsepbottom](https://github.com/nvim-zh/colorful-winsep.nvim/assets/89089655/6b289882-7a73-4f08-bac0-9b117d62ff44)

The issue is really in the 2nd image. However, if you compare the first and the 2nd image, theres actually a tiny gap in the winsepartor that doesnt get highlighted at all. 

Turning off my status line plugins and playing with laststatus doesn't really change anything.

And this bug is only for 2 vertically split screens. All other behaviour still works perfectly and I love this plugin sosososo much.

![win](https://github.com/nvim-zh/colorful-winsep.nvim/assets/89089655/ebbe900f-9afd-48d8-8ea5-0bb11c0713b5)

**Comment by denstiny** [comment]
oh，This is easy to solve, but I'm too busy recently. Maybe you can try to submit a pr.

**Comment by denstiny** [comment]
https://github.com/nvim-zh/colorful-winsep.nvim/pull/52
