### ISSUE TITLE
Vertical split and selecting right window breaks global statusline

### ISSUE THREAD

**Issue by ebkalderon** [nvim-zh/colorful-winsep.nvim#51]
Thanks for the awesome plugin! It seems this plugin doesn't quite interact correctly with a global statusline (`vim.opt.laststatus = 3`), if one is present. As shown in the screenshot below, creating a vertical split and then selecting the window on the right causes the statusline to be split in half. This example uses [lualine.nvim](https://github.com/nvim-lualine/lualine.nvim) with `options.globalstatus = true`.

### 1. Create vertical split

![Screenshot from 2023-05-28 21-13-30](https://github.com/nvim-zh/colorful-winsep.nvim/assets/322831/b1df91bd-2565-47f9-ad74-4285a4dc29a4)

### 2. Select window on right (statusline is accidentally split)

![Screenshot from 2023-05-28 21-13-35](https://github.com/nvim-zh/colorful-winsep.nvim/assets/322831/52307930-36be-4327-9edb-cc0b19939e06)

**Comment by denstiny** [comment]
https://github.com/nvim-zh/colorful-winsep.nvim/pull/52

**Comment by ebkalderon** [comment]
Thanks for the fix, @denstiny! I'll try it locally later today and close this ticket when confirmed.

**Comment by acehinnnqru** [comment]
@ebkalderon Is it working well?

**Comment by bsong0** [comment]
> @ebkalderon Is it working well?

Hi, I am facing this problem again today, 
![image](https://github.com/nvim-zh/colorful-winsep.nvim/assets/85090456/658ab170-92a8-4d02-9d57-51c6b16c9d45)
Config:
```
    {
        "nvim-zh/colorful-winsep.nvim",
        config = true,
        event = { "WinNew" },
    },
```

**Comment by denstiny** [comment]
> > @ebkalderon Is it working well?
> 
> Hi, I am facing this problem again today, ![image](https://user-images.githubusercontent.com/85090456/256207722-658ab170-92a8-4d02-9d57-51c6b16c9d45.png) Config:
> 
> ```
>     {
>         "nvim-zh/colorful-winsep.nvim",
>         config = true,
>         event = { "WinNew" },
>     },
> ```

why

**Comment by denstiny** [comment]
Everything is ok on it in my computer

**Comment by serranomorante** [comment]
Same here, it has something to do with neo-tree but no idea. My config is same as the colorful-winsep README.

![t-rec_17](https://github.com/nvim-zh/colorful-winsep.nvim/assets/43413954/c00202ef-a0b9-40ef-9242-b7157d707626)

**Comment by allenfrostline** [comment]
@serranomorante I'm encountering the same issue. Have you found a solution yet?

**Comment by serranomorante** [comment]
> @serranomorante I'm encountering the same issue. Have you found a solution yet?

Sorry, I stopped using `neotree.nvim` and just embraced the vim way.
Recommended readings.
[The project drawer](http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/)
[About windows, buffers and tabs](https://stackoverflow.com/a/26710166)

**Comment by denstiny** [comment]
In order to better analyze the problem, I need your neovim option.lua

**Comment by denstiny** [comment]
> Same here, it has something to do with neo-tree but no idea. My config is same as the colorful-winsep README.
> 
> ![t-rec_17](https://private-user-images.githubusercontent.com/43413954/270485338-c00202ef-a0b9-40ef-9242-b7157d707626.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjM2MjMsIm5iZiI6MTcwODYyMzMyMywicGF0aCI6Ii80MzQxMzk1NC8yNzA0ODUzMzgtYzAwMjAyZWYtYTBiOS00MGVmLTkyNDItYjcxNTdkNzA3NjI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE3MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczN2VhZWVlMGExODE3YmNkMTNlYzYxYWUyZDBmMzM0MmM0MWJmZmMwOTBhYmM3NzMwMWU2Y2RlZDkwMGVmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQ92C-vc3cmEUlCM3zte2bi05EySLqTwjSxKvB8tLYY) [ ![t-rec_17](https://private-user-images.githubusercontent.com/43413954/270485338-c00202ef-a0b9-40ef-9242-b7157d707626.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjM2MjMsIm5iZiI6MTcwODYyMzMyMywicGF0aCI6Ii80MzQxMzk1NC8yNzA0ODUzMzgtYzAwMjAyZWYtYTBiOS00MGVmLTkyNDItYjcxNTdkNzA3NjI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE3MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczN2VhZWVlMGExODE3YmNkMTNlYzYxYWUyZDBmMzM0MmM0MWJmZmMwOTBhYmM3NzMwMWU2Y2RlZDkwMGVmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQ92C-vc3cmEUlCM3zte2bi05EySLqTwjSxKvB8tLYY) ](https://private-user-images.githubusercontent.com/43413954/270485338-c00202ef-a0b9-40ef-9242-b7157d707626.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjM2MjMsIm5iZiI6MTcwODYyMzMyMywicGF0aCI6Ii80MzQxMzk1NC8yNzA0ODUzMzgtYzAwMjAyZWYtYTBiOS00MGVmLTkyNDItYjcxNTdkNzA3NjI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE3MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczN2VhZWVlMGExODE3YmNkMTNlYzYxYWUyZDBmMzM0MmM0MWJmZmMwOTBhYmM3NzMwMWU2Y2RlZDkwMGVmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQ92C-vc3cmEUlCM3zte2bi05EySLqTwjSxKvB8tLYY) [ ](https://private-user-images.githubusercontent.com/43413954/270485338-c00202ef-a0b9-40ef-9242-b7157d707626.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjM2MjMsIm5iZiI6MTcwODYyMzMyMywicGF0aCI6Ii80MzQxMzk1NC8yNzA0ODUzMzgtYzAwMjAyZWYtYTBiOS00MGVmLTkyNDItYjcxNTdkNzA3NjI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE3MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczN2VhZWVlMGExODE3YmNkMTNlYzYxYWUyZDBmMzM0MmM0MWJmZmMwOTBhYmM3NzMwMWU2Y2RlZDkwMGVmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQ92C-vc3cmEUlCM3zte2bi05EySLqTwjSxKvB8tLYY)

Nothing to do with winsep configuration, I need your neovim option.lua

**Comment by denstiny** [comment]
> @serranomorante I'm encountering the same issue. Have you found a solution yet?

Nothing to do with winsep configuration, I need your neovim option.lua

**Comment by denstiny** [comment]
> > > @ebkalderon Is it working well?
> > 
> > 
> > Hi, I am facing this problem again today, ![image](https://user-images.githubusercontent.com/85090456/256207722-658ab170-92a8-4d02-9d57-51c6b16c9d45.png) Config:
> > ```
> >     {
> >         "nvim-zh/colorful-winsep.nvim",
> >         config = true,
> >         event = { "WinNew" },
> >     },
> > ```
> 
> why

 I need your neovim option.lua
