### ISSUE TITLE
Opening `q:` will show an error

### ISSUE THREAD

**Issue by Amar1729** [nvim-zh/colorful-winsep.nvim#53]
I think the code has been refactored a bit since the last issue mentioning this: https://github.com/nvim-zh/colorful-winsep.nvim/issues/27

I have `colorful-winsep` configured via `lazy.nvim` to load on the `WinNew` event. The first time in a particular buffer I open the command `q:` window, it opens fine. The second time however, the follow error is shown:

```
   Error  23:38:08 msg_show.lua_error    Error executing vim.schedule lua callback: ...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:72: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
	[C]: in function 'nvim_buf_delete'
	...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:72: in function 'close_dividing'
	...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:16: in function 'create_dividing_win'
	...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:151: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

If I remove the `event = { "WinNew" }`, the error is simply shown starting with first time I open the command window after opening vim.

Maybe this is due to calling `nvim_buf_delete` on the command window? I looked into the stacktrace but i'm not really sure what's going on. Looks like there's already some special logic for handling a wintype of `"command"` in some of the relevant functions.

----

minimal config below (copped from the `lazy.nvim` minimal `repro.lua`, you can run this with `nvim -u repro.lua`:

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here

  {
    "nvim-zh/colorful-winsep.nvim",
    event = { "WinNew" },
    opts = { highlight = { ctermfg = 2 } },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by SomesOver** [comment]
I can't recreate

**Comment by SomesOver** [comment]
> 我认为自上一期提到这一点以来代码已经被重构了一些： [ #27 ](https://github.com/nvim-zh/colorful-winsep.nvim/issues/27)
> 
> 我有 `colorful-winsep`配置通过 `lazy.nvim`加载到 `WinNew`事件。 第一次在特定缓冲区中打开命令 `q:`窗口，打开很好。 但是第二次出现以下错误：
> 
> ```
>    Error  23:38:08 msg_show.lua_error    Error executing vim.schedule lua callback: ...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:72: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
> stack traceback:
> 	[C]: in function 'nvim_buf_delete'
> 	...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:72: in function 'close_dividing'
> 	...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:16: in function 'create_dividing_win'
> 	...m/lazy/colorful-winsep.nvim/lua/colorful-winsep/view.lua:151: in function ''
> 	vim/_editor.lua: in function <vim/_editor.lua:0>
> ```
> 
> 如果我删除 `event = { "WinNew" }`，从我打开 vim 后第一次打开命令窗口开始，错误就简单地显示了。
> 
> 也许这是由于调用 `nvim_buf_delete`在命令窗口上？ 我查看了堆栈跟踪，但我不太确定发生了什么。 看起来已经有一些特殊的逻辑来处理 wintype `"command"`在一些相关的功能中。
> 
> 下面的最小配置（从 `lazy.nvim`最小的 `repro.lua`，你可以运行它 `nvim -u repro.lua`:
> 
> ```lua
> -- DO NOT change the paths and don't remove the colorscheme
> local root = vim.fn.fnamemodify("./.repro", ":p")
> 
> -- set stdpaths to use .repro
> for _, name in ipairs({ "config", "data", "state", "cache" }) do
>   vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
> end
> 
> -- bootstrap lazy
> local lazypath = root .. "/plugins/lazy.nvim"
> if not vim.loop.fs_stat(lazypath) then
>   vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
> end
> vim.opt.runtimepath:prepend(lazypath)
> 
> -- install plugins
> local plugins = {
>   "folke/tokyonight.nvim",
>   -- add any other plugins here
> 
>   {
>     "nvim-zh/colorful-winsep.nvim",
>     event = { "WinNew" },
>     opts = { highlight = { ctermfg = 2 } },
>   },
> }
> require("lazy").setup(plugins, {
>   root = root .. "/plugins",
> })
> 
> vim.cmd.colorscheme("tokyonight")
> ```

I can't recreate

**Comment by denstiny** [comment]
Try using your alpha branch
