### ISSUE TITLE
Border of top panel overlaps bottom panel

### ISSUE THREAD

**Issue by SylEleuth** [nvim-zh/colorful-winsep.nvim#55]
https://github.com/nvim-zh/colorful-winsep.nvim/assets/33354262/29660cd9-ab4b-4b7f-81c9-675a78a62924

Minimal config:
```
local fn = vim.fn
local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
vim.opt.laststatus = 3

if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({
    'git',
    'clone',
    '--depth',
    '1',
    'https://github.com/wbthomason/packer.nvim',
    install_path
  })
  vim.o.runtimepath = vim.fn.stdpath('data') .. '/site/pack/*/start/*,' .. vim.o.runtimepath
end

vim.cmd [[
  augroup packer_user_config
    autocmd!
    autocmd BufWritePost packer_init.lua source <afile> | PackerSync
  augroup end
]]

local status_ok, packer = pcall(require, 'packer')
if not status_ok then
  return
end

packer.init {
  display = {
    open_fn = function()
      return require("packer.util").float { border = "rounded" }
    end,
  },
  git = {
    clone_timeout = 300, -- Timeout, in seconds, for git clones
  },
}

return packer.startup(function(use)

use {
    "nvim-zh/colorful-winsep.nvim",
    config = function ()
        require('colorful-winsep').setup()
    end
}

  if packer_bootstrap then
    require('packer').sync()
  end
end)
```

**Comment by denstiny** [comment]
you should adjust the anchor parameters, which is better suited to everyone's configuration, see the alpha branch documentation to help

**Comment by denstiny** [comment]
Or you can fix the branch to the main branch, now the default branch is alpha, but main will no longer be updated

**Comment by SylEleuth** [comment]
Indeed it helped. Thank You.
In case anyone else have the same problem here is my config:
```
  anchor = {
    left = { height = 0, x = -1, y = -1 },
    right = { height = 0, x = -1, y = 0 },
    up = { width = 0, x = -1, y = 0 },
    bottom = { width = 0, x = 0, y = 0 },
  },

```
It also fixes an issue when vertical separator breaks global statusline (which You can see on the video above).

**Comment by denstiny** [comment]
> Indeed it helped. Thank You. In case anyone else have the same problem here is my config:
> 
> ```
>   anchor = {
>     left = { height = 0, x = -1, y = -1 },
>     right = { height = 0, x = -1, y = 0 },
>     up = { width = 0, x = -1, y = 0 },
>     bottom = { width = 0, x = 0, y = 0 },
>   },
> ```
> 
> It also fixes an issue when vertical separator breaks global statusline (which You can see on the video above).

I think that's the right thing to do, rather than adapt everyone's configuration, let everyone adjust the parameters

Thank you very much for your question
