### ISSUE TITLE
Over-extending background

### ISSUE THREAD

**Issue by v-tibi** [nvim-zh/colorful-winsep.nvim#61]
Winsep is installed with a mostly stock Lazy.nvim installation. I'm using Neovim v0.9.5.

The problem is the background of the horizontal separator extends to 2 lines of height. When a pane at the top is selected it is always 2 lines high and covers the first line of the pane below. When a pane at the bottom is selected the separator is 1 line high until the content of the pane is scrolled to the top, when it extends to 2 lines too.

![Screenshot from 2024-04-26 16-48-43](https://github.com/nvim-zh/colorful-winsep.nvim/assets/43302788/85d242c4-7f51-4f16-adae-b6696851bf50)

![Screenshot from 2024-04-26 16-48-54](https://github.com/nvim-zh/colorful-winsep.nvim/assets/43302788/1b75dd9e-1848-46d0-bff4-fd3d33ecf37a)

![Screenshot from 2024-04-26 16-48-59](https://github.com/nvim-zh/colorful-winsep.nvim/assets/43302788/1d5f054f-6bf4-4dfd-8762-bd21025ff59a)

**Comment by denstiny** [comment]
already fixed
