### ISSUE TITLE
incorrect divider set on autosession load w/nvimtree

### ISSUE THREAD

**Issue by Rydwxz** [nvim-zh/colorful-winsep.nvim#68]
It looks like it may be being placed where buffer is before nvim-tree is toggled on. When nvimtree is toggled on without being focused in the post session load hook, the divider isn't updated? 
![scrnsht](https://github.com/nvim-zh/colorful-winsep.nvim/assets/114803384/537a45a3-cd19-48bf-9202-cc21af83ae96)

[minimum reproducible config](https://github.com/Rydwxz/nvim-config/tree/debug)

**Comment by denstiny** [comment]
```lua
events = { "WinEnter", "BufEnter", "WinResized", "WinClosed", "VimResized", "SessionLoadPost" },
```

**Comment by Rydwxz** [comment]
Thank you for your input, but I'm not certain what to do with that. I changed `event = { "WinNew"},` to `events = { "WinEnter", "BufEnter", "WinResized", "WinClosed", "VimResized", "SessionLoadPost" },` as well as `events = { "WinEnter", "SessionLoadPost",},` but the divider still appears in the same spot, only now it is white instead of the hl I set in the config.

**Comment by denstiny** [comment]
> Thank you for your input, but I'm not certain what to do with that. I changed `event = { "WinNew"},` to `events = { "WinEnter", "BufEnter", "WinResized", "WinClosed", "VimResized", "SessionLoadPost" },` as well as `events = { "WinEnter", "SessionLoadPost",},` but the divider still appears in the same spot, only now it is normal fg color instead of the hl I set in the config. I tried these lines with and without the `s`on the end of `event` and I also tried removing the line entirely.

https://github.com/denstiny/dotfiles/blob/eb1216edd268dbc85f9d8597a89c97b67dea36c0/nvim/lua/plugin/ui/init.lua#L51-L59
 this is my config.

**Comment by denstiny** [comment]
Don't forget to check out my require"plugin.ui.winsep" content

**Comment by timtyrrell** [comment]
I have been experiencing the same issue, although I can trigger the problem without using sessions. Anytime I run `:NvimTreeToggle`, `:NvimTreeFindFile`, or `:NvimTreeToggle` it happens. I tried all of the even configs mentioned above but it had no effect.

**Comment by denstiny** [comment]
> I have been experiencing the same issue, although I can trigger the problem without using sessions. Anytime I run `:NvimTreeToggle`, `:NvimTreeFindFile`, or `:NvimTreeToggle` it happens. I tried all of the event configs mentioned above but it had no effect.

Can you please provide the minimum reproducible configuration and reproduction steps?

**Comment by timtyrrell** [comment]
@denstiny I figured out it. Removing `NvimTree` from the `no_exec_files` array fixed it. Maybe I don't have the same issue here and I apologize. Let me know if you want me to open a new issue and I can copy this over. 

Steps to duplicate:
- use mini.vim
- `:e file1`
- `:vsp`
- `:NvimTreeToggle`


<details>
<summary>mini.vim</summary>
set nocompatible
filetype plugin indent on
syntax on
set hidden

call plug#begin('~/.config/nvim/plugged')

Plug 'nvim-zh/colorful-winsep.nvim'
Plug 'kyazdani42/nvim-tree.lua'

call plug#end()

lua << EOF

require("colorful-winsep").setup({
  no_exec_files = { "NvimTree" },
  -- either one of these events arrays causes the issue
  -- events = { "VimResume", "WinEnter", "BufEnter", "WinResized", "WinClosed", "VimResized", "SessionLoadPost" },
  event = { "WinNew" },
})

require('nvim-tree').setup { }

EOF
</details>

**Comment by denstiny** [comment]
> @denstiny I figured out it. Removing `NvimTree` from the `no_exec_files` array fixed it. Maybe I don't have the same issue here and I apologize. Let me know if you want me to open a new issue and I can copy this over.
> 
> Steps to duplicate:
> 
>     * use mini.vim
> 
>     * `:e file1`
> 
>     * `:vsp`
> 
>     * `:NvimTreeToggle`
> 
> 
> mini.vim
> set nocompatible filetype plugin indent on syntax on set hidden
> 
> call plug#begin('~/.config/nvim/plugged')
> 
> Plug 'nvim-zh/colorful-winsep.nvim' Plug 'kyazdani42/nvim-tree.lua'
> 
> call plug#end()
> 
> lua << EOF
> 
> require("colorful-winsep").setup({ no_exec_files = { "NvimTree" }, -- either one of these events arrays causes the issue -- events = { "VimResume", "WinEnter", "BufEnter", "WinResized", "WinClosed", "VimResized", "SessionLoadPost" }, event = { "WinNew" }, })
> 
> require('nvim-tree').setup { }
> 
> EOF
Well, this is because after opening the window for nvim-tree, there are other behaviors that exist. The no_exec_files option can fix this. Since I personally use nvim-tree as well as Session, I am quite confused about this issue and have been unable to reproduce the problem

**Comment by denstiny** [comment]
@timtyrrell Furthermore, for the lazy-loading of this plugin, I believe you should use the WinLeave event rather than the WinNew event.

**Comment by denstiny** [comment]
https://github.com/nvim-zh/colorful-winsep.nvim/assets/57088952/0b8a52e4-9b63-4b42-8cd5-01d12176fc63
