### ISSUE TITLE
neo-tree `auto_expand_width = true` causes separator to display over top of neo-tree when it expands wider

### ISSUE THREAD

**Issue by jondkinney** [nvim-zh/colorful-winsep.nvim#73]
Like the title says, the separator shows up fine initially, but then when neo-tree resizes due to a folder with long file names opening up, it doesn't adjust.

![CleanShot 2024-08-26 at 10 41 29@2x](https://github.com/user-attachments/assets/b7e390af-7d76-4ee5-9b7c-ba847f80fdaa)

**Comment by beyond-fu** [comment]
Same bug to me!

**Comment by denstiny** [comment]
i see

**Comment by denstiny** [comment]
Neovim cannot read the WinResize event modified by defer_fn that changes the window size, which leads to the inability to redraw the window. I am currently unsure how to resolve this issue.

**Comment by denstiny** [comment]
"Can you provide a solution?" @jondkinney

**Comment by micsama** [comment]
> "Can you provide a solution?" @jondkinney
I often resize Neo-tree manually by map like res -5.
maybe someone can add a lazy refresh into the plugin?
add a command to refresh the line Manually？
because we can map some key like: <CMD>res -5<CR><CMD>refresh_line<CR>

or add an choice to refresh line every second?

**Comment by micsama** [comment]
> > "Can you provide a solution?" @jondkinney
> > I often resize Neo-tree manually by map like res -5.
> > maybe someone can add a lazy refresh into the plugin?
> > add a command to refresh the line Manually？
> > because we can map some key like: res -5refresh_line
> 
> or add an choice to refresh line every second?
I think we need to add the cmd map, because sometimes when I close a term window below, the line will not refresh too

**Comment by denstiny** [comment]
Disable no_exec_files for neo-tree, which by default excludes events for neo-tree file types.

**Comment by denstiny** [comment]
@jondkinney  @micsama Check the no_exec_files list.
