### ISSUE TITLE
The separator blocked nvim-window-picker message

### ISSUE THREAD

**Issue by adoyle-h** [nvim-zh/colorful-winsep.nvim#74]
Hi, I find a bug that using the https://github.com/s1n7ax/nvim-window-picker and colorful-winsep.nvim, the separator blocked window-picker message.

![2024-09-09_22 40 06@2x](https://github.com/user-attachments/assets/b1695f5d-0d93-4849-9f54-fdd589b50145)

How to fix it? Thanks.

**Comment by denstiny** [comment]
"This is a window sorting issue; the sorting of winsep is set to the lowest. If window-picker is willing to increase the z-index value of the window, this problem can be resolved.“

**Comment by adoyle-h** [comment]
The window-picker just set value for statusline. https://github.com/s1n7ax/nvim-window-picker/blob/41cfaa428577c53552200a404ae9b3a0b5719706/lua/window-picker/hints/statusline-hint.lua#L77
The statusline seems have not z-index. @denstiny

**Comment by denstiny** [comment]
> The window-picker just set value for statusline. https://github.com/s1n7ax/nvim-window-picker/blob/41cfaa428577c53552200a404ae9b3a0b5719706/lua/window-picker/hints/statusline-hint.lua#L77
> The statusline seems have not z-index. @denstiny 

you can search api.nvim_open_win code from window-pixcker

**Comment by adoyle-h** [comment]
https://github.com/s1n7ax/nvim-window-picker/blob/41cfaa428577c53552200a404ae9b3a0b5719706/lua/window-picker/hints/floating-big-letter-hint.lua#L110

The api.nvim_open_win used for floating-big-letter-hint. The nvim-window-picker has two modes: `hint = 'statusline-winbar'` and `hint = 'floating-big-letter'`.
The floating-big-letter opens new window to show floating big letter, and the statusline-winbar change the text in statusline. And I'm using `hint = 'statusline-winbar'`.

**Comment by adoyle-h** [comment]
@denstiny 
Could you provide functions to turn on/off the colorful-winsep? So I can turn off colorful-winsep before `window-picker.pick_window()`. For example,

```lua
function() {
		local picker = require('window-picker')
		local winsep = require('colorful-winsep')
		winsep.disable()
		local picked_window_id = picker.pick_window()
		winsep.enable()
		vim.api.nvim_set_current_win(picked_window_id)
}
```

**Comment by adoyle-h** [comment]
I submitted a PR. Please review it. Thanks.

**Comment by denstiny** [comment]
> I submitted a PR. Please review it. Thanks.

Hi,you can add render() api, Thanks.
