### ISSUE TITLE
Hide border for nvim-tree

### ISSUE THREAD

**Issue by rocktimsaikia** [nvim-zh/colorful-winsep.nvim#8]
How can I hide the border colour when there is only one window opened including the [nvim-tree](https://github.com/nvim-tree/nvim-tree.lua) border?
![image](https://user-images.githubusercontent.com/33410545/199205155-028479b0-f130-48f8-9c7b-9a38a916ebc2.png)

**Comment by rocktimsaikia** [comment]
I have already tried that too before creating the issue but didn't seem to work
![image](https://user-images.githubusercontent.com/33410545/199212899-0ff5168d-38a2-404c-96dc-f54ddaacd895.png)

**Comment by denstiny** [comment]
Sorry, this feature has not been considered for the time being

**Comment by denstiny** [comment]
In the future I will provide enable and disable api, this issue is no longer within my consideration

**Comment by denstiny** [comment]
hi, I added create_event and close_event ,Now you can achieve your requirement by following method

```lua
  create_event = function()
    if vim.fn.winnr('$') == 2 then
      local win_id = vim.fn.win_getid(vim.fn.winnr('h'))
      local filetype = api.nvim_buf_get_option(vim.api.nvim_win_get_buf(win_id), 'filetype')
      if filetype == "NvimTree" then
        colorful_winsep.NvimSeparatorDel()
      end
    end
  end
```
